name: Deploy to cPanel Web Disk

on:
  push:
    branches:
      - dashboard

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add build steps here if needed, e.g.:
      # - name: Install dependencies
      #   run: npm install
      # - name: Build project
      #   run: npm run build

      - name: Deploy to cPanel Web Disk via WebDAV
        env:
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          # Find all files except those in the files/ directory at root
          find . -type f ! -path "./.git/*" ! -path "./.github/*" ! -path "./files/*" | while read file; do
            remote_path="${file#./}"
            # Create directory structure if needed (WebDAV requires directories to exist)
            if [[ "$remote_path" == *"/"* ]]; then
              dir_path=$(dirname "$remote_path")
              curl -u "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" -X MKCOL --create-dirs "$WEBDAV_URL/$dir_path" || true
            fi
            # Upload file
            curl -T "$file" --user "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" "$WEBDAV_URL/$remote_path"
          done